# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_domain_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='specialist',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=picklefield.fields.PickledObjectField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='specialist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_avis', to='blog.Specialist'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
