# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170929_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='specialist',
        ),
    ]
