# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170929_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
