# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170929_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_avis', to='blog.Specialist'),
        ),
    ]
