# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meta_description',
            new_name='avis',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='geocode',
            new_name='address_geocode',
        ),
    ]
