# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsearch', '0002_auto_20170930_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
