# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsearch', '0003_auto_20170930_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='address_geocode',
            new_name='geocode',
        ),
    ]
