# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsearch', '0005_domain_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='image_path',
            new_name='imagePath',
        ),
    ]
